Update to mousegen 0.4
Fixes run-time dependency issue manifesting like:

    java.lang.NoClassDefFoundError: org/apache/batik/transcoder/SVGAbstractTranscoder
            ...
            at io.github.stanio.mousegen.RendererBackend.<clinit>(RendererBackend.java:65)
            at io.github.stanio.mousegen.CursorRenderer.<init>(CursorRenderer.java:76)
            at io.github.stanio.mousegen.MouseGen.<init>(MouseGen.java:72)
            at io.github.stanio.mousegen.MouseGen.main(MouseGen.java:290)
            at io.github.stanio.mousegen.Command.main(Command.java:38)
    Caused by: java.lang.ClassNotFoundException: org.apache.batik.transcoder.SVGAbstractTranscoder
            ...

when Batik jars are not present, even when not used (by default).

  + Bump Bibata version for next development: 2.0.7-stanio-8-dev